# Only take care the members will be used in oasis-ssvm-runtime
[workspace]
members = [
	"core",
	"http",
	# "ipc",
	"macros",
	# "minihttp",
	"pubsub",
	# "pubsub/more-examples",
	# "server-utils",
	# "stdio",
	# "tcp",
	# "test",
	"ws",
]
